### ISSUE TITLE
Getting wrong temp1_max resulting CPU to stay at Coolfreq

### ISSUE THREAD

**Issue by zzecool** [Trauma/cpufreq-userspace-scaler#4]
Hi there im attaching a screenshot to explain the script behaviour.

![CPU_freq](https://user-images.githubusercontent.com/2816897/116400551-d9276180-a832-11eb-939e-9c27d1f99d38.jpg)

- Until the first red arrow the script isn't running on the DS918+ so the default CPU freq is 1501
- After the first red arrow and the Script is running but as the temp1_max is 105 the script using `cut -c 1-2` is thinking that the temp1_max is 10 degrees so it is running always in Coolfreq =1300
- After the second red arrow i modified and rerun the script using `cut -c 1-3` for the temp1_max resulting in proper exucution of the code.

Kind regards.

**Comment by Trauma** [comment]
same as https://github.com/Trauma/cpufreq-userspace-scaler/commit/6b86097a5a95c33e49efc81ec2cbaff9ef1e70c1#r48044621

**Comment by Trauma** [comment]
Fix backported in master 68749ff
